//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.0
//     from Packages/com.sk.libretro/Unity/LibretroInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace SK.Libretro.Unity
{
    public partial class @LibretroInputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @LibretroInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""LibretroInputActions"",
    ""maps"": [
        {
            ""name"": ""RetroPad"",
            ""id"": ""639a1fe9-28e1-41ea-a98f-20b729bf505d"",
            ""actions"": [
                {
                    ""name"": ""DPadUp"",
                    ""type"": ""Button"",
                    ""id"": ""3d136013-1adf-4a01-ad86-7e5f4e85dd81"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""DPadDown"",
                    ""type"": ""Button"",
                    ""id"": ""7760eb09-40c3-407b-a78f-b921cfb12220"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""DPadLeft"",
                    ""type"": ""Button"",
                    ""id"": ""0038abb7-866b-4663-ba18-2ba0d91d8278"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""DPadRight"",
                    ""type"": ""Button"",
                    ""id"": ""5be0e20d-0a38-4110-b69d-2c12222af05d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""AnalogLeft"",
                    ""type"": ""Value"",
                    ""id"": ""37eaa882-3108-46cb-9d25-c58cbc04245c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""AnalogRight"",
                    ""type"": ""Value"",
                    ""id"": ""13b7bb8d-03e0-4bab-90ed-96c8fba076ff"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""9c24f261-5878-4731-84f6-c78c63030707"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""f36bdbe8-984d-4ee1-828f-09864532efd2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""A"",
                    ""type"": ""Button"",
                    ""id"": ""e53ba5ed-7472-4b78-84c0-1fb5090f8c02"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""B"",
                    ""type"": ""Button"",
                    ""id"": ""43910c93-05e7-444e-a9a2-e9672dc24851"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""X"",
                    ""type"": ""Button"",
                    ""id"": ""e4753e14-08e3-4a66-8300-14400a4ac68f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Y"",
                    ""type"": ""Button"",
                    ""id"": ""b06fcc7f-56a6-474b-8210-8542c0a84670"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""L1"",
                    ""type"": ""Button"",
                    ""id"": ""7b0cf759-77c7-4989-9771-c92f0d252cbe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""L2"",
                    ""type"": ""Button"",
                    ""id"": ""056ab63b-501f-43c2-b9ef-6f18ba200cbc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""L3"",
                    ""type"": ""Button"",
                    ""id"": ""e24819fc-988c-4580-b3f3-5cf81d5bc5f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""R1"",
                    ""type"": ""Button"",
                    ""id"": ""818c3450-ed6f-43c4-b028-bd2e462d9531"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""R2"",
                    ""type"": ""Button"",
                    ""id"": ""53f451b1-0b6c-4fb3-aa44-e9adb960fde3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""R3"",
                    ""type"": ""Button"",
                    ""id"": ""c370147f-9b2e-4df5-94d7-ee55bbf96f12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""MousePositionDelta"",
                    ""type"": ""Value"",
                    ""id"": ""d1bb5935-abc8-408f-8be9-e7c13106d47f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""MouseWheelDelta"",
                    ""type"": ""Value"",
                    ""id"": ""d4393c8f-ae26-43d5-a210-aada0d924e9c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""MouseLeftButton"",
                    ""type"": ""Button"",
                    ""id"": ""fb5fe1ab-4f43-4283-aa33-979f65f561f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""MouseRightButton"",
                    ""type"": ""Button"",
                    ""id"": ""0f8e30f0-b439-4f01-b0d1-a44602b472a9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""MouseMiddleButton"",
                    ""type"": ""Button"",
                    ""id"": ""d083c22f-6003-497b-b429-a6768fdd427c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""MouseForwardButton"",
                    ""type"": ""Button"",
                    ""id"": ""717e1b43-c43a-483a-b741-74bcebf873c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""MouseBackButton"",
                    ""type"": ""Button"",
                    ""id"": ""2dd72a4a-66e3-4798-a075-6bb2dc2960bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""LightgunTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""bc140f6d-c2ac-4e47-bca9-ad46748bcfde"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""LightgunReload"",
                    ""type"": ""Button"",
                    ""id"": ""eac3b4ee-8d56-4893-ba75-5cda41228de3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""LightgunA"",
                    ""type"": ""Button"",
                    ""id"": ""0467163e-355e-4a82-84e3-4855efd6d92b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""LightgunB"",
                    ""type"": ""Button"",
                    ""id"": ""7303ab29-d32f-45f0-89c7-7f17d1f7b1ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""LightgunStart"",
                    ""type"": ""Button"",
                    ""id"": ""fff3d153-08ee-454d-a52b-5a6cd3b76b7b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""LightgunSelect"",
                    ""type"": ""Button"",
                    ""id"": ""10f049bf-4f20-4a2c-8b1d-37570583ff8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""LightgunC"",
                    ""type"": ""Button"",
                    ""id"": ""e111be7a-5b8f-47db-a495-6311ea7dd4ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""LightgunDPadUp"",
                    ""type"": ""Button"",
                    ""id"": ""dd466b88-1632-4dc5-a4cb-a1d0b3b0903b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""LightgunDPadDown"",
                    ""type"": ""Button"",
                    ""id"": ""32f32150-5c72-43af-ad7f-24b8bada2936"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""LightgunDPadLeft"",
                    ""type"": ""Button"",
                    ""id"": ""002905db-5ec3-4424-9e01-b5a787fd1aa0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""LightgunDPadRight"",
                    ""type"": ""Button"",
                    ""id"": ""d313664d-baef-43df-ab01-2001f9cf7cc8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2c219cb1-24e1-4536-b0b7-a043e6996c4e"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05314db2-fc53-4007-908e-4cefbcaded21"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ea933b0-6174-42ee-a12a-6f7d357aa7d0"",
                    ""path"": ""<XRController>{RightHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9038026f-a11d-4b46-8642-914319aecbc9"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a8b16ce-e843-4273-8290-27d71cd99c61"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c131ee0-c595-43fc-a143-9c5e43b95c69"",
                    ""path"": ""<XRController>{LeftHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76e05051-e233-44a1-9eb1-124f5865a557"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3ccd30f-77fc-4578-a8df-c0913f9a0453"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3743692-239c-4b7b-9746-23dd06c20933"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44f0fbc6-b559-44f1-8e7d-388a1016ea72"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96354b97-ed6e-4294-ad85-4cf0aa8b7f0f"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61173740-6cfb-488d-a57d-dcddd1a8a2e5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""820b1e80-9a18-4d8b-b1f0-4560a4ce68b0"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3450d917-02c1-4d26-8b1d-aba6efce683d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e8cf6e5-d265-48c0-b522-6ef65b9841ab"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""R3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27e6739e-e46c-40a1-b371-c209c58baaed"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""R3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d818302f-e70c-439a-93f3-29729ffc2709"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bff5f60b-7033-4c2b-b8cb-7e960accda4c"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02fb5cb1-3d62-4a8e-8530-0bb7a5a3c268"",
                    ""path"": ""<XRController>{RightHand}/gripButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5bc3b7e-58b2-4333-a557-4bcaff47c53e"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d902525-a63f-45ba-b8b1-ec4e35f59b2f"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b358726c-25e2-40e1-bd6d-79111e19370b"",
                    ""path"": ""<XRController>{RightHand}/triggerButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86528e80-6a72-441b-9a7e-0f59f081e5d4"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""457ca745-3ab0-479b-b09a-174382947b59"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e4af279-b67c-44ba-9114-2c2bb4443087"",
                    ""path"": ""<XRController>{LeftHand}/triggerButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7173dc3-17d0-49f2-917b-a1713f08362d"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f2fe01b-53ad-4bc4-95d6-f91356467e79"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16513cee-8da6-4c7b-8bdc-5ca07f6186d3"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b04b3254-45f7-42ff-91e7-3ee94dd070f1"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d1cea9a-b937-4dab-af57-6f7703f0f3e5"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""429553a0-14fc-40f3-b9d1-510f4cef06ba"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b057da26-acc6-4521-a361-fc48dedc8a4a"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""MousePositionDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c01ed5f5-ff06-4b6b-b483-0f7f6d5306f3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""MouseLeftButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8db7c5c-9c9f-4f4a-bd9d-7f3db65545a9"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""MouseRightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6eebfaf6-8f0c-4277-8c84-1e64f3173785"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""MouseMiddleButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3701c51-43c9-420a-bb40-1eab9a0a0d8b"",
                    ""path"": ""<Mouse>/forwardButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""MouseForwardButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e66ff22-9651-4278-a6cf-39a8c28c7d34"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""MouseBackButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5fdf7fa4-a6c6-4349-80bf-0b243f538620"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""MouseWheelDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""a86c4a94-0270-4007-a825-dfb4278da3b0"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogLeft"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d066947d-869b-4ef5-b12b-d8171c6afe14"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""AnalogLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""daf19ca1-8e59-4594-82a0-bd296f51d482"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""AnalogLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b518a295-89a9-4b8a-8179-5561175b5bf8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""AnalogLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a6bdebb2-50ff-429c-9cef-81bbe52b8e8a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""AnalogLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d61bc526-6350-4903-9427-f6a576f1e9a4"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AnalogLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12b93b2d-ef7c-495e-8400-18978b281845"",
                    ""path"": ""<XRController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""AnalogLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""IKJL"",
                    ""id"": ""e95e7196-0734-475d-ae26-f7b0c6aa1582"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogRight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""cf8ebc26-77fa-499b-a4ea-e5e5218eb32d"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""AnalogRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3f569a55-dab6-47d6-97ef-c28dedfd468a"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""AnalogRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""60cf206a-56f5-419c-91aa-f56afe63057e"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""AnalogRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""994a6d7d-5036-4f03-a20a-47821f7b1326"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""AnalogRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3179612d-a9f1-4d05-883e-64bf98cd238e"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AnalogRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ec89672-1ba9-4c81-8014-b9f6b95907e5"",
                    ""path"": ""<XRController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""AnalogRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d80c12b-1749-473c-9c2c-c60fa0590331"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""L3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eebd950f-62b4-42d1-bc9c-ecf76e78bb42"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""L3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77e966b4-1ecd-432d-a7a8-0d1c9de4abfb"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82af4109-f72d-433e-82b4-7031442c1b89"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""471051bd-efc7-4e4e-ac3e-afb0f033ecfe"",
                    ""path"": ""<XRController>{LeftHand}/gripButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91e7e295-43ac-43d9-bdc9-044d75dda63f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""LightgunTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85800c01-af61-4abc-8c9c-6ef465837d70"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""LightgunReload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac2a0d9a-4e02-4dce-9c86-47cb677eff1c"",
                    ""path"": ""<Mouse>/forwardButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""LightgunA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74b61b12-8059-4823-95a5-e635897360eb"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""LightgunB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28bb9b16-04dd-4c4f-bbff-3a972dbb3987"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""LightgunStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3df2d2d-8fa5-4655-8d16-a448bb05f1e1"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""LightgunSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a153d70-dd42-41b1-82f5-ae1b4e975b61"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""LightgunC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39b9493b-02f3-4dac-938c-17ba6c578494"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""LightgunDPadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ccf8a83-c278-41c8-92e4-f5c1a5c776c2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""LightgunDPadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""223fd5e2-324e-4edc-a646-34705107f79b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""LightgunDPadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38cc1711-f2d0-434d-8eff-f71badabba71"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""LightgunDPadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fb74aca-a35e-4887-be90-a798484f9d10"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""DPadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e4bfa4c-2f5b-47c1-be23-f7165b0e3428"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DPadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a17f978-8bdb-4d31-bc39-d5fd572e77ef"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""DPadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""230461db-1d18-44ea-9a15-1d547cf4240f"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DPadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97dd8eff-ba4f-4ba1-934b-0bf2cef3c74a"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""DPadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""652d77f2-235f-4679-9261-07daced0c825"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DPadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb860a80-924c-4f55-8e39-40adf38973e3"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""DPadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61cd0271-1bdf-4f41-86c2-7edba6738adc"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DPadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard & Mouse"",
            ""bindingGroup"": ""Keyboard & Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XRController>{LeftHand}"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XRController>{RightHand}"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // RetroPad
            m_RetroPad = asset.FindActionMap("RetroPad", throwIfNotFound: true);
            m_RetroPad_DPadUp = m_RetroPad.FindAction("DPadUp", throwIfNotFound: true);
            m_RetroPad_DPadDown = m_RetroPad.FindAction("DPadDown", throwIfNotFound: true);
            m_RetroPad_DPadLeft = m_RetroPad.FindAction("DPadLeft", throwIfNotFound: true);
            m_RetroPad_DPadRight = m_RetroPad.FindAction("DPadRight", throwIfNotFound: true);
            m_RetroPad_AnalogLeft = m_RetroPad.FindAction("AnalogLeft", throwIfNotFound: true);
            m_RetroPad_AnalogRight = m_RetroPad.FindAction("AnalogRight", throwIfNotFound: true);
            m_RetroPad_Start = m_RetroPad.FindAction("Start", throwIfNotFound: true);
            m_RetroPad_Select = m_RetroPad.FindAction("Select", throwIfNotFound: true);
            m_RetroPad_A = m_RetroPad.FindAction("A", throwIfNotFound: true);
            m_RetroPad_B = m_RetroPad.FindAction("B", throwIfNotFound: true);
            m_RetroPad_X = m_RetroPad.FindAction("X", throwIfNotFound: true);
            m_RetroPad_Y = m_RetroPad.FindAction("Y", throwIfNotFound: true);
            m_RetroPad_L1 = m_RetroPad.FindAction("L1", throwIfNotFound: true);
            m_RetroPad_L2 = m_RetroPad.FindAction("L2", throwIfNotFound: true);
            m_RetroPad_L3 = m_RetroPad.FindAction("L3", throwIfNotFound: true);
            m_RetroPad_R1 = m_RetroPad.FindAction("R1", throwIfNotFound: true);
            m_RetroPad_R2 = m_RetroPad.FindAction("R2", throwIfNotFound: true);
            m_RetroPad_R3 = m_RetroPad.FindAction("R3", throwIfNotFound: true);
            m_RetroPad_MousePositionDelta = m_RetroPad.FindAction("MousePositionDelta", throwIfNotFound: true);
            m_RetroPad_MouseWheelDelta = m_RetroPad.FindAction("MouseWheelDelta", throwIfNotFound: true);
            m_RetroPad_MouseLeftButton = m_RetroPad.FindAction("MouseLeftButton", throwIfNotFound: true);
            m_RetroPad_MouseRightButton = m_RetroPad.FindAction("MouseRightButton", throwIfNotFound: true);
            m_RetroPad_MouseMiddleButton = m_RetroPad.FindAction("MouseMiddleButton", throwIfNotFound: true);
            m_RetroPad_MouseForwardButton = m_RetroPad.FindAction("MouseForwardButton", throwIfNotFound: true);
            m_RetroPad_MouseBackButton = m_RetroPad.FindAction("MouseBackButton", throwIfNotFound: true);
            m_RetroPad_LightgunTrigger = m_RetroPad.FindAction("LightgunTrigger", throwIfNotFound: true);
            m_RetroPad_LightgunReload = m_RetroPad.FindAction("LightgunReload", throwIfNotFound: true);
            m_RetroPad_LightgunA = m_RetroPad.FindAction("LightgunA", throwIfNotFound: true);
            m_RetroPad_LightgunB = m_RetroPad.FindAction("LightgunB", throwIfNotFound: true);
            m_RetroPad_LightgunStart = m_RetroPad.FindAction("LightgunStart", throwIfNotFound: true);
            m_RetroPad_LightgunSelect = m_RetroPad.FindAction("LightgunSelect", throwIfNotFound: true);
            m_RetroPad_LightgunC = m_RetroPad.FindAction("LightgunC", throwIfNotFound: true);
            m_RetroPad_LightgunDPadUp = m_RetroPad.FindAction("LightgunDPadUp", throwIfNotFound: true);
            m_RetroPad_LightgunDPadDown = m_RetroPad.FindAction("LightgunDPadDown", throwIfNotFound: true);
            m_RetroPad_LightgunDPadLeft = m_RetroPad.FindAction("LightgunDPadLeft", throwIfNotFound: true);
            m_RetroPad_LightgunDPadRight = m_RetroPad.FindAction("LightgunDPadRight", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // RetroPad
        private readonly InputActionMap m_RetroPad;
        private IRetroPadActions m_RetroPadActionsCallbackInterface;
        private readonly InputAction m_RetroPad_DPadUp;
        private readonly InputAction m_RetroPad_DPadDown;
        private readonly InputAction m_RetroPad_DPadLeft;
        private readonly InputAction m_RetroPad_DPadRight;
        private readonly InputAction m_RetroPad_AnalogLeft;
        private readonly InputAction m_RetroPad_AnalogRight;
        private readonly InputAction m_RetroPad_Start;
        private readonly InputAction m_RetroPad_Select;
        private readonly InputAction m_RetroPad_A;
        private readonly InputAction m_RetroPad_B;
        private readonly InputAction m_RetroPad_X;
        private readonly InputAction m_RetroPad_Y;
        private readonly InputAction m_RetroPad_L1;
        private readonly InputAction m_RetroPad_L2;
        private readonly InputAction m_RetroPad_L3;
        private readonly InputAction m_RetroPad_R1;
        private readonly InputAction m_RetroPad_R2;
        private readonly InputAction m_RetroPad_R3;
        private readonly InputAction m_RetroPad_MousePositionDelta;
        private readonly InputAction m_RetroPad_MouseWheelDelta;
        private readonly InputAction m_RetroPad_MouseLeftButton;
        private readonly InputAction m_RetroPad_MouseRightButton;
        private readonly InputAction m_RetroPad_MouseMiddleButton;
        private readonly InputAction m_RetroPad_MouseForwardButton;
        private readonly InputAction m_RetroPad_MouseBackButton;
        private readonly InputAction m_RetroPad_LightgunTrigger;
        private readonly InputAction m_RetroPad_LightgunReload;
        private readonly InputAction m_RetroPad_LightgunA;
        private readonly InputAction m_RetroPad_LightgunB;
        private readonly InputAction m_RetroPad_LightgunStart;
        private readonly InputAction m_RetroPad_LightgunSelect;
        private readonly InputAction m_RetroPad_LightgunC;
        private readonly InputAction m_RetroPad_LightgunDPadUp;
        private readonly InputAction m_RetroPad_LightgunDPadDown;
        private readonly InputAction m_RetroPad_LightgunDPadLeft;
        private readonly InputAction m_RetroPad_LightgunDPadRight;
        public struct RetroPadActions
        {
            private @LibretroInputActions m_Wrapper;
            public RetroPadActions(@LibretroInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @DPadUp => m_Wrapper.m_RetroPad_DPadUp;
            public InputAction @DPadDown => m_Wrapper.m_RetroPad_DPadDown;
            public InputAction @DPadLeft => m_Wrapper.m_RetroPad_DPadLeft;
            public InputAction @DPadRight => m_Wrapper.m_RetroPad_DPadRight;
            public InputAction @AnalogLeft => m_Wrapper.m_RetroPad_AnalogLeft;
            public InputAction @AnalogRight => m_Wrapper.m_RetroPad_AnalogRight;
            public InputAction @Start => m_Wrapper.m_RetroPad_Start;
            public InputAction @Select => m_Wrapper.m_RetroPad_Select;
            public InputAction @A => m_Wrapper.m_RetroPad_A;
            public InputAction @B => m_Wrapper.m_RetroPad_B;
            public InputAction @X => m_Wrapper.m_RetroPad_X;
            public InputAction @Y => m_Wrapper.m_RetroPad_Y;
            public InputAction @L1 => m_Wrapper.m_RetroPad_L1;
            public InputAction @L2 => m_Wrapper.m_RetroPad_L2;
            public InputAction @L3 => m_Wrapper.m_RetroPad_L3;
            public InputAction @R1 => m_Wrapper.m_RetroPad_R1;
            public InputAction @R2 => m_Wrapper.m_RetroPad_R2;
            public InputAction @R3 => m_Wrapper.m_RetroPad_R3;
            public InputAction @MousePositionDelta => m_Wrapper.m_RetroPad_MousePositionDelta;
            public InputAction @MouseWheelDelta => m_Wrapper.m_RetroPad_MouseWheelDelta;
            public InputAction @MouseLeftButton => m_Wrapper.m_RetroPad_MouseLeftButton;
            public InputAction @MouseRightButton => m_Wrapper.m_RetroPad_MouseRightButton;
            public InputAction @MouseMiddleButton => m_Wrapper.m_RetroPad_MouseMiddleButton;
            public InputAction @MouseForwardButton => m_Wrapper.m_RetroPad_MouseForwardButton;
            public InputAction @MouseBackButton => m_Wrapper.m_RetroPad_MouseBackButton;
            public InputAction @LightgunTrigger => m_Wrapper.m_RetroPad_LightgunTrigger;
            public InputAction @LightgunReload => m_Wrapper.m_RetroPad_LightgunReload;
            public InputAction @LightgunA => m_Wrapper.m_RetroPad_LightgunA;
            public InputAction @LightgunB => m_Wrapper.m_RetroPad_LightgunB;
            public InputAction @LightgunStart => m_Wrapper.m_RetroPad_LightgunStart;
            public InputAction @LightgunSelect => m_Wrapper.m_RetroPad_LightgunSelect;
            public InputAction @LightgunC => m_Wrapper.m_RetroPad_LightgunC;
            public InputAction @LightgunDPadUp => m_Wrapper.m_RetroPad_LightgunDPadUp;
            public InputAction @LightgunDPadDown => m_Wrapper.m_RetroPad_LightgunDPadDown;
            public InputAction @LightgunDPadLeft => m_Wrapper.m_RetroPad_LightgunDPadLeft;
            public InputAction @LightgunDPadRight => m_Wrapper.m_RetroPad_LightgunDPadRight;
            public InputActionMap Get() { return m_Wrapper.m_RetroPad; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(RetroPadActions set) { return set.Get(); }
            public void SetCallbacks(IRetroPadActions instance)
            {
                if (m_Wrapper.m_RetroPadActionsCallbackInterface != null)
                {
                    @DPadUp.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnDPadUp;
                    @DPadUp.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnDPadUp;
                    @DPadUp.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnDPadUp;
                    @DPadDown.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnDPadDown;
                    @DPadDown.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnDPadDown;
                    @DPadDown.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnDPadDown;
                    @DPadLeft.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnDPadLeft;
                    @DPadLeft.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnDPadLeft;
                    @DPadLeft.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnDPadLeft;
                    @DPadRight.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnDPadRight;
                    @DPadRight.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnDPadRight;
                    @DPadRight.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnDPadRight;
                    @AnalogLeft.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnAnalogLeft;
                    @AnalogLeft.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnAnalogLeft;
                    @AnalogLeft.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnAnalogLeft;
                    @AnalogRight.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnAnalogRight;
                    @AnalogRight.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnAnalogRight;
                    @AnalogRight.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnAnalogRight;
                    @Start.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnStart;
                    @Start.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnStart;
                    @Start.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnStart;
                    @Select.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnSelect;
                    @Select.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnSelect;
                    @Select.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnSelect;
                    @A.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnA;
                    @A.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnA;
                    @A.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnA;
                    @B.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnB;
                    @B.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnB;
                    @B.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnB;
                    @X.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnX;
                    @X.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnX;
                    @X.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnX;
                    @Y.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnY;
                    @Y.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnY;
                    @Y.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnY;
                    @L1.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnL1;
                    @L1.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnL1;
                    @L1.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnL1;
                    @L2.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnL2;
                    @L2.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnL2;
                    @L2.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnL2;
                    @L3.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnL3;
                    @L3.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnL3;
                    @L3.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnL3;
                    @R1.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnR1;
                    @R1.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnR1;
                    @R1.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnR1;
                    @R2.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnR2;
                    @R2.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnR2;
                    @R2.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnR2;
                    @R3.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnR3;
                    @R3.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnR3;
                    @R3.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnR3;
                    @MousePositionDelta.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMousePositionDelta;
                    @MousePositionDelta.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMousePositionDelta;
                    @MousePositionDelta.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMousePositionDelta;
                    @MouseWheelDelta.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseWheelDelta;
                    @MouseWheelDelta.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseWheelDelta;
                    @MouseWheelDelta.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseWheelDelta;
                    @MouseLeftButton.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseLeftButton;
                    @MouseLeftButton.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseLeftButton;
                    @MouseLeftButton.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseLeftButton;
                    @MouseRightButton.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseRightButton;
                    @MouseRightButton.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseRightButton;
                    @MouseRightButton.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseRightButton;
                    @MouseMiddleButton.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseMiddleButton;
                    @MouseMiddleButton.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseMiddleButton;
                    @MouseMiddleButton.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseMiddleButton;
                    @MouseForwardButton.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseForwardButton;
                    @MouseForwardButton.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseForwardButton;
                    @MouseForwardButton.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseForwardButton;
                    @MouseBackButton.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseBackButton;
                    @MouseBackButton.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseBackButton;
                    @MouseBackButton.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnMouseBackButton;
                    @LightgunTrigger.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunTrigger;
                    @LightgunTrigger.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunTrigger;
                    @LightgunTrigger.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunTrigger;
                    @LightgunReload.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunReload;
                    @LightgunReload.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunReload;
                    @LightgunReload.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunReload;
                    @LightgunA.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunA;
                    @LightgunA.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunA;
                    @LightgunA.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunA;
                    @LightgunB.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunB;
                    @LightgunB.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunB;
                    @LightgunB.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunB;
                    @LightgunStart.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunStart;
                    @LightgunStart.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunStart;
                    @LightgunStart.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunStart;
                    @LightgunSelect.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunSelect;
                    @LightgunSelect.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunSelect;
                    @LightgunSelect.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunSelect;
                    @LightgunC.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunC;
                    @LightgunC.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunC;
                    @LightgunC.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunC;
                    @LightgunDPadUp.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunDPadUp;
                    @LightgunDPadUp.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunDPadUp;
                    @LightgunDPadUp.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunDPadUp;
                    @LightgunDPadDown.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunDPadDown;
                    @LightgunDPadDown.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunDPadDown;
                    @LightgunDPadDown.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunDPadDown;
                    @LightgunDPadLeft.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunDPadLeft;
                    @LightgunDPadLeft.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunDPadLeft;
                    @LightgunDPadLeft.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunDPadLeft;
                    @LightgunDPadRight.started -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunDPadRight;
                    @LightgunDPadRight.performed -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunDPadRight;
                    @LightgunDPadRight.canceled -= m_Wrapper.m_RetroPadActionsCallbackInterface.OnLightgunDPadRight;
                }
                m_Wrapper.m_RetroPadActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @DPadUp.started += instance.OnDPadUp;
                    @DPadUp.performed += instance.OnDPadUp;
                    @DPadUp.canceled += instance.OnDPadUp;
                    @DPadDown.started += instance.OnDPadDown;
                    @DPadDown.performed += instance.OnDPadDown;
                    @DPadDown.canceled += instance.OnDPadDown;
                    @DPadLeft.started += instance.OnDPadLeft;
                    @DPadLeft.performed += instance.OnDPadLeft;
                    @DPadLeft.canceled += instance.OnDPadLeft;
                    @DPadRight.started += instance.OnDPadRight;
                    @DPadRight.performed += instance.OnDPadRight;
                    @DPadRight.canceled += instance.OnDPadRight;
                    @AnalogLeft.started += instance.OnAnalogLeft;
                    @AnalogLeft.performed += instance.OnAnalogLeft;
                    @AnalogLeft.canceled += instance.OnAnalogLeft;
                    @AnalogRight.started += instance.OnAnalogRight;
                    @AnalogRight.performed += instance.OnAnalogRight;
                    @AnalogRight.canceled += instance.OnAnalogRight;
                    @Start.started += instance.OnStart;
                    @Start.performed += instance.OnStart;
                    @Start.canceled += instance.OnStart;
                    @Select.started += instance.OnSelect;
                    @Select.performed += instance.OnSelect;
                    @Select.canceled += instance.OnSelect;
                    @A.started += instance.OnA;
                    @A.performed += instance.OnA;
                    @A.canceled += instance.OnA;
                    @B.started += instance.OnB;
                    @B.performed += instance.OnB;
                    @B.canceled += instance.OnB;
                    @X.started += instance.OnX;
                    @X.performed += instance.OnX;
                    @X.canceled += instance.OnX;
                    @Y.started += instance.OnY;
                    @Y.performed += instance.OnY;
                    @Y.canceled += instance.OnY;
                    @L1.started += instance.OnL1;
                    @L1.performed += instance.OnL1;
                    @L1.canceled += instance.OnL1;
                    @L2.started += instance.OnL2;
                    @L2.performed += instance.OnL2;
                    @L2.canceled += instance.OnL2;
                    @L3.started += instance.OnL3;
                    @L3.performed += instance.OnL3;
                    @L3.canceled += instance.OnL3;
                    @R1.started += instance.OnR1;
                    @R1.performed += instance.OnR1;
                    @R1.canceled += instance.OnR1;
                    @R2.started += instance.OnR2;
                    @R2.performed += instance.OnR2;
                    @R2.canceled += instance.OnR2;
                    @R3.started += instance.OnR3;
                    @R3.performed += instance.OnR3;
                    @R3.canceled += instance.OnR3;
                    @MousePositionDelta.started += instance.OnMousePositionDelta;
                    @MousePositionDelta.performed += instance.OnMousePositionDelta;
                    @MousePositionDelta.canceled += instance.OnMousePositionDelta;
                    @MouseWheelDelta.started += instance.OnMouseWheelDelta;
                    @MouseWheelDelta.performed += instance.OnMouseWheelDelta;
                    @MouseWheelDelta.canceled += instance.OnMouseWheelDelta;
                    @MouseLeftButton.started += instance.OnMouseLeftButton;
                    @MouseLeftButton.performed += instance.OnMouseLeftButton;
                    @MouseLeftButton.canceled += instance.OnMouseLeftButton;
                    @MouseRightButton.started += instance.OnMouseRightButton;
                    @MouseRightButton.performed += instance.OnMouseRightButton;
                    @MouseRightButton.canceled += instance.OnMouseRightButton;
                    @MouseMiddleButton.started += instance.OnMouseMiddleButton;
                    @MouseMiddleButton.performed += instance.OnMouseMiddleButton;
                    @MouseMiddleButton.canceled += instance.OnMouseMiddleButton;
                    @MouseForwardButton.started += instance.OnMouseForwardButton;
                    @MouseForwardButton.performed += instance.OnMouseForwardButton;
                    @MouseForwardButton.canceled += instance.OnMouseForwardButton;
                    @MouseBackButton.started += instance.OnMouseBackButton;
                    @MouseBackButton.performed += instance.OnMouseBackButton;
                    @MouseBackButton.canceled += instance.OnMouseBackButton;
                    @LightgunTrigger.started += instance.OnLightgunTrigger;
                    @LightgunTrigger.performed += instance.OnLightgunTrigger;
                    @LightgunTrigger.canceled += instance.OnLightgunTrigger;
                    @LightgunReload.started += instance.OnLightgunReload;
                    @LightgunReload.performed += instance.OnLightgunReload;
                    @LightgunReload.canceled += instance.OnLightgunReload;
                    @LightgunA.started += instance.OnLightgunA;
                    @LightgunA.performed += instance.OnLightgunA;
                    @LightgunA.canceled += instance.OnLightgunA;
                    @LightgunB.started += instance.OnLightgunB;
                    @LightgunB.performed += instance.OnLightgunB;
                    @LightgunB.canceled += instance.OnLightgunB;
                    @LightgunStart.started += instance.OnLightgunStart;
                    @LightgunStart.performed += instance.OnLightgunStart;
                    @LightgunStart.canceled += instance.OnLightgunStart;
                    @LightgunSelect.started += instance.OnLightgunSelect;
                    @LightgunSelect.performed += instance.OnLightgunSelect;
                    @LightgunSelect.canceled += instance.OnLightgunSelect;
                    @LightgunC.started += instance.OnLightgunC;
                    @LightgunC.performed += instance.OnLightgunC;
                    @LightgunC.canceled += instance.OnLightgunC;
                    @LightgunDPadUp.started += instance.OnLightgunDPadUp;
                    @LightgunDPadUp.performed += instance.OnLightgunDPadUp;
                    @LightgunDPadUp.canceled += instance.OnLightgunDPadUp;
                    @LightgunDPadDown.started += instance.OnLightgunDPadDown;
                    @LightgunDPadDown.performed += instance.OnLightgunDPadDown;
                    @LightgunDPadDown.canceled += instance.OnLightgunDPadDown;
                    @LightgunDPadLeft.started += instance.OnLightgunDPadLeft;
                    @LightgunDPadLeft.performed += instance.OnLightgunDPadLeft;
                    @LightgunDPadLeft.canceled += instance.OnLightgunDPadLeft;
                    @LightgunDPadRight.started += instance.OnLightgunDPadRight;
                    @LightgunDPadRight.performed += instance.OnLightgunDPadRight;
                    @LightgunDPadRight.canceled += instance.OnLightgunDPadRight;
                }
            }
        }
        public RetroPadActions @RetroPad => new RetroPadActions(this);
        private int m_KeyboardMouseSchemeIndex = -1;
        public InputControlScheme KeyboardMouseScheme
        {
            get
            {
                if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard & Mouse");
                return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        public interface IRetroPadActions
        {
            void OnDPadUp(InputAction.CallbackContext context);
            void OnDPadDown(InputAction.CallbackContext context);
            void OnDPadLeft(InputAction.CallbackContext context);
            void OnDPadRight(InputAction.CallbackContext context);
            void OnAnalogLeft(InputAction.CallbackContext context);
            void OnAnalogRight(InputAction.CallbackContext context);
            void OnStart(InputAction.CallbackContext context);
            void OnSelect(InputAction.CallbackContext context);
            void OnA(InputAction.CallbackContext context);
            void OnB(InputAction.CallbackContext context);
            void OnX(InputAction.CallbackContext context);
            void OnY(InputAction.CallbackContext context);
            void OnL1(InputAction.CallbackContext context);
            void OnL2(InputAction.CallbackContext context);
            void OnL3(InputAction.CallbackContext context);
            void OnR1(InputAction.CallbackContext context);
            void OnR2(InputAction.CallbackContext context);
            void OnR3(InputAction.CallbackContext context);
            void OnMousePositionDelta(InputAction.CallbackContext context);
            void OnMouseWheelDelta(InputAction.CallbackContext context);
            void OnMouseLeftButton(InputAction.CallbackContext context);
            void OnMouseRightButton(InputAction.CallbackContext context);
            void OnMouseMiddleButton(InputAction.CallbackContext context);
            void OnMouseForwardButton(InputAction.CallbackContext context);
            void OnMouseBackButton(InputAction.CallbackContext context);
            void OnLightgunTrigger(InputAction.CallbackContext context);
            void OnLightgunReload(InputAction.CallbackContext context);
            void OnLightgunA(InputAction.CallbackContext context);
            void OnLightgunB(InputAction.CallbackContext context);
            void OnLightgunStart(InputAction.CallbackContext context);
            void OnLightgunSelect(InputAction.CallbackContext context);
            void OnLightgunC(InputAction.CallbackContext context);
            void OnLightgunDPadUp(InputAction.CallbackContext context);
            void OnLightgunDPadDown(InputAction.CallbackContext context);
            void OnLightgunDPadLeft(InputAction.CallbackContext context);
            void OnLightgunDPadRight(InputAction.CallbackContext context);
        }
    }
}
